apiVersion: apps/v1
kind: Deployment
metadata:
  name: followers-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: followers
  template:
    metadata:
      labels:
        app: followers
    spec:
      containers:
        - name: followers
          image: ivanovb3/followers
          env:
            - name: MONGO_URI
              value: 'mongodb://followers-mongo-srv:27017/followers'
            - name: JWT_KEY
              valueFrom:  
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'kwetter'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: followers-srv
spec:
  selector:
    app: followers
  ports:
    - name: followers
      protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: followers-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: followers-depl
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 400Mi