apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profiles
  template:
    metadata:
      labels:
        app: profiles
    spec:
      containers:
        - name: profiles
          image: ivanovb3/profiles
          env:
            - name: MONGO_URI
              value: 'mongodb://profiles-mongo-srv:27017/profiles'
            - name: JWT_KEY
              valueFrom:  
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'kwetter'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: S3_ACCESS_KEY
              value: 'AKIAT3OTUDKPSLCJLE76'
            - name: S3_SECRET_KEY
              value: '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'
            - name: S3_BUCKET_REGION
              value: 'eu-central-1'
---
apiVersion: v1
kind: Service
metadata:
  name: profiles-srv
spec:
  selector:
    app: profiles
  ports:
    - name: profiles
      protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: profiles-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: profiles-depl
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 400Mi