apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweets
  template:
    metadata:
      labels:
        app: tweets
    spec:
      containers:
        - name: tweets
          image: ivanovb3/tweets
          env:
            - name: MONGO_URI
              value: 'mongodb://tweets-mongo-srv:27017/tweets'
            - name: JWT_KEY
              valueFrom:  
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'kwetter'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: tweets-srv
spec:
  selector:
    app: tweets
  ports:
    - name: tweets
      protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: tweets-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tweets-depl
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 400Mi