@startuml blogging_context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("v1.1 - later stage", $fontColor="#d73027", $bgColor=$CONTAINER_BG_COLOR)

Person(user, "User", "Regular user who uses the social platform")
Person(admin, "Administrator", "Resposible for managing user's roles and accounts")
Person(moderator, "Moderator", "User responsible for protecting application's regulations")

Container(frontend, "Web Application", "React", "The user intefrace used to share information with other people")
Container(frontendmods, "Web Application", "React", "The admin and moderator interface used to manage users")
Container(backend, "API Gateway", "Spring", "Microservice gateway handles all business logic")

ContainerDb(usersdb, "Users database", "MySQL", "Holds user information")
ContainerDb(tweetsdb, "Tweets database", "MySQL", "Contains tweets, comments")
ContainerDb(followersdb, "Followers database", "MySQL", "Contains relationships between users (follows)")

Rel(user, frontend, "Uses")
Rel(admin, frontendmods, "Uses")
Rel(moderator, frontendmods, "Uses")
Rel(frontendmods, backend, "Uses", "HTTPS/JSON")
Rel(frontend, backend, "Uses", "HTTPS/JSON")
Rel(backend, usersdb, "Reads/Writes")
Rel(backend, tweetsdb, "Reads/Writes")
Rel(backend, followersdb, "Reads/Writes")

SHOW_LEGEND()
@enduml