name: Client

on:
  push:
    branches: [ master ]
    paths: 'client/**'
    
env:
  REGISTRY_NAME: kwetterDeploymentACR
  APP_NAME: client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./comments
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/comments:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Connect to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }} 
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Container build and push to a Azure Container Registry (ACR)
        run: |
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        working-directory: ./client


