name: Followers

on:
  push:
    branches: [ master ]
    paths: 'followers/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./followers
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/followers:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
