name: test-auth

on:
  pull_request:
    paths: 
      - 'auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0
      - run: cd auth && npm install && node --experimental-vm-modules node_modules/jest/bin/jest.js
      # - uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    
  
