name: test-reacts

on:
  pull_request:
    paths: 
      - 'reacts/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd reacts && npm install && node --experimental-vm-modules node_modules/jest/bin/jest.js
