name: test-tweets

on:
  pull_request:
    paths: 
      - 'tweets/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tweets && npm install && node --experimental-vm-modules node_modules/jest/bin/jest.js
