name: test-auth

on:
  push:
    branches: 
      - 'master'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install && node --experimental-vm-modules node_modules/jest/bin/jest.js
    
  
