name: tests

on:
  push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm install && node --experimental-vm-modules node_modules/jest/bin/jest.js:ci
    
  
