name: test-organizations

on:
  pull_request:
    paths: 
      - 'organizations/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd organizations && npm install && node --experimental-vm-modules node_modules/jest/bin/jest.js
